[workspace]
members = [
    "proto_convert_derive",
    "proto_convert_build",
    "grpc-example",
]
resolver = "2"

[workspace.package]
publish = false
version = "0.2.0"
edition = "2021"

[workspace.metadata.crane]
name = "proto-convert-workspace"
