name: Nix Flake Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            /nix/var/nix
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Run Nix Flake Check
        run: |
          nix flake check # --print-build-logs
